### ISSUE TITLE
Topic injection doesn't support the default cluster.

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious-junit5-extension#240]
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**

**To Reproduce**
1. Use kroxylicious-junit5-extension release 0.7.0 
2. run this test

```java
package io.kroxylicious.proxy;

import java.time.Duration;
import java.util.Set;
import java.util.concurrent.ExecutionException;

import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import io.kroxylicious.testing.kafka.junit5ext.KafkaClusterExtension;
import io.kroxylicious.testing.kafka.junit5ext.Topic;

@ExtendWith(KafkaClusterExtension.class)
class ExampleTest {

    @Test
    void shouldConsumePublishedRecord(Topic topic, Producer<String, String> producer, Consumer<String, String> consumer)
            throws ExecutionException, InterruptedException {
        //Given
        producer.send(new ProducerRecord<>(topic.name(), "my-key", "Hello, world!")).get();
        consumer.subscribe(Set.of(topic.name()));

        //When
        var records = consumer.poll(Duration.ofSeconds(10));

        //Then
        consumer.close();
        Assertions.assertThat(records).hasSize(1).extractingResultOf("value").containsExactly("Hello, world!");
    }
}
```

3. Fails with
```
io.kroxylicious.testing.kafka.junit5ext.AmbiguousKafkaClusterException: KafkaCluster to associate with parameter topic is ambiguous, use @Name on the intended cluster and this element to disambiguate

	at io.kroxylicious.testing.kafka.junit5ext.KafkaClusterExtension.findClusterFromContext(KafkaClusterExtension.java:822)
	at io.kroxylicious.testing.kafka.junit5ext.KafkaClusterExtension.createTopic(KafkaClusterExtension.java:1003)
	at io.kroxylicious.testing.kafka.junit5ext.KafkaClusterExtension.resolveParameter(KafkaClusterExtension.java:518)
	at io.kroxylicious.testing.kafka.junit5ext.KafkaClusterExtension.resolveParameter(KafkaClusterExtension.java:470)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Expected behavior**
The topic to be injected onto the default cluster.

**Logs**

Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
Ah.. I didn't even know a default cluster was a thing!  Judging by the tests within `io.kroxylicious.testing.kafka.junit5ext` we don't have any tests for it either.

**Comment by k-wall** [comment]
Are you sure it is even a thing? I see no mention in the README or Javadoc and from a quick glance in the code, I don't see implementation supporting that..  #getCluster is only called on the fields and parameter paths.

All these tests fail in the same way.

```java
@ExtendWith(KafkaClusterExtension.class)
public class DefaultClusterTest extends AbstractExtensionTest {

    @Test
    void admin(Admin admin) {
        Assertions.assertThat(admin).isNotNull();
    }

    @Test
    void consumer(Consumer<String, String> consumer) {
        Assertions.assertThat(consumer).isNotNull();
    }

    @Test
    void producer(Producer<String, String> producer) {
        Assertions.assertThat(producer).isNotNull();
    }

    @Test
    void topic(Topic topic) {
        Assertions.assertThat(topic).isNotNull();
    }
}
```

**Comment by SamBarker** [comment]
Hmm, maybe it's just the KroxyliciousTester that does default clusters.
