### ISSUE TITLE
ParameterExtensionTest#clusterParameter: Socket server failed to bind to 0.0.0.0:49164: Address already in use.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious-junit5-extension#29]
Maybe 20% of the time I see a failure like this:

```
TESTCONTAINERS_RYUK_DISABLED=true mvn verify -Dmaven.javadoc.skip=true
```

```
[ERROR] io.kroxylicious.testing.kafka.junit5ext.ParameterExtensionTest.clusterParameter(KafkaCluster)  Time elapsed: 0.502 s  <<< ERROR!
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [io.kroxylicious.testing.kafka.api.KafkaCluster cluster] in method [public void io.kroxylicious.testing.kafka.junit5ext.ParameterExtensionTest.clusterParameter(io.kroxylicious.testing.kafka.api.KafkaCluster) throws java.util.concurrent.ExecutionException,java.lang.InterruptedException]: org.apache.kafka.common.KafkaException: Socket server failed to bind to 0.0.0.0:49164: Address already in use.
```

```
Caused by: org.apache.kafka.common.KafkaException: Socket server failed to bind to 0.0.0.0:49164: Address already in use.
	at kafka.network.Acceptor.openServerSocket(SocketServer.scala:684)
	at kafka.network.Acceptor.<init>(SocketServer.scala:576)
	at kafka.network.DataPlaneAcceptor.<init>(SocketServer.scala:433)
	at kafka.network.SocketServer.createDataPlaneAcceptor(SocketServer.scala:247)
	at kafka.network.SocketServer.createDataPlaneAcceptorAndProcessors(SocketServer.scala:226)
	at kafka.network.SocketServer.$anonfun$new$29(SocketServer.scala:170)
	at kafka.network.SocketServer.$anonfun$new$29$adapted(SocketServer.scala:170)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at kafka.network.SocketServer.<init>(SocketServer.scala:170)
	at kafka.server.ControllerServer.startup(ControllerServer.scala:165)
	at kafka.server.KafkaRaftServer.$anonfun$startup$1(KafkaRaftServer.scala:140)
	at kafka.server.KafkaRaftServer.$anonfun$startup$1$adapted(KafkaRaftServer.scala:140)
	at scala.Option.foreach(Option.scala:437)
	at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:140)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:459)
	at java.base/sun.nio.ch.Net.bind(Net.java:448)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at kafka.network.Acceptor.openServerSocket(SocketServer.scala:680)
	... 25 more
```

**Comment by k-wall** [comment]
@SamBarker repeated calls to preAllocateListeningPorts would certainly give you a good chance of a port conflict.  It was designed to be called once .  I suppose you could reimplement as a PortAllocator object so you avoid having to splice up the array.

```
try (var pa = new PortAllocater()) {
  var x = pa.getPorts(5);   # internally build an array of open server sockets.
  var y = pa.getPorts(10);
  pa.close();  # close would close the close the server sockets.
}
```


https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/ee5966bef02b5a5f07fb8d4864db2335114619c8/impl/src/main/java/io/kroxylicious/testing/kafka/invm/InVMKafkaCluster.java#L58

**Comment by SamBarker** [comment]
@k-wall A port allocator might be the right answer but in #26 I went for returning the sockets and keeping them alive for longer. Which seems to fix this instance. 

Running in intellij I configured `ParameterExtensionTest` to repeat until failure.
- main: 1/10 tests fail
- pr26: 100 tests run 0 failures

So I think we mergePR #26 now and can revisit later once things are stable.

**Comment by k-wall** [comment]
> A port allocator might be the right answer but in https://github.com/kroxylicious/kroxylicious-junit5-extension/pull/26 I went for returning the sockets and keeping them alive for longer.

@SamBarker  I don't see how your change keeps the sockets open for longer than before.  You are still using try-with-resources.  That closes the socket.   The backlog value is the default.  The sockets will already be closed before you reach your new release call. Maybe  explicit bind to all network interfaces is somehow material or just the wind is blowing slightly differently today.

**Comment by SamBarker** [comment]
hmmm I had miss-understood the impact of returning the socket... 

It certainly keeps the socket object alive longer, I wonder if that has some impact even if close has already been called or maybe as you say the wind was blowing differently...

**Comment by k-wall** [comment]
I guess it depends on how the TCP/IP stack goes about reusing previously used ephemeral port numbers..  who knows? I don't.   switching to a pattern where we allocate all ports first then release en-masse should safest.  

Always binding to port 0 would be perfect, but there are reasons (advertised listeners) why this won't work with Kraft based kafka right now.
