### ISSUE TITLE
Interop with `@ParameterizedTest`'s parameter providers

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious-junit5-extension#62]
I have a test with a structure like the following:

```java
@ExtendWith(KafkaClusterExtension.class)
public class MyTest {
    KafkaCluster kafkaCluster;
    Admin admin;

    public static Args[] argsForTest() {
        // ...
    }

    @ParameterizedTest
    @MethodSource("argsForTest")
    public void test(Args args) {
        // ...
    }
}
```

That works fine so long as I actually want the same `kafkaCluster` for all the `@ParameterizedTest`-annotated methods in the class. If I have a single test which needs a different configuration of cluster then I _ought_ to be able to:

1. Remove the `KafkaCluster kafkaCluster` field
2. Declare a parameter `KafkaCluster kafkaCluster` on each test method instead

But this does work in practice because:

1. The extension is too opinionated about fields (specifically it sees the `Admin admin` field, thinks it needs to manage it itself and then barfs because it doesn't have a same-or-outer-scoped `KafkaCluster to hook it up to).
2. Even if you work around 1. by using a wrapper type unknown to the extension (e.g. `AtomicReference<Admin>`) then you hit the fact that `@MethodSource` (or more correctly `org.junit.jupiter.params.provider.MethodArgumentsProvider`) expects to own the entire argument list, but in this case we want it to only take responsibility for those arguments which `KafkaClusterExtension` is not responsible for.

For reference the stacktrace starts like this:

> org.junit.jupiter.api.extension.ParameterResolutionException: Discovered multiple competing ParameterResolvers for parameter [io.kroxylicious.testing.kafka.api.KafkaCluster arg0] in method [public void io.strimzi.operator.topic.v2.TopicControllerIT.shouldCreateTopicInKafkaWhenManagedTopicCreatedInKube(io.kroxylicious.testing.kafka.api.KafkaCluster,io.strimzi.api.kafka.model.KafkaTopic) throws java.util.concurrent.ExecutionException,java.lang.InterruptedException]: io.kroxylicious.testing.kafka.junit5ext.KafkaClusterExtension@7bce9ce4, org.junit.jupiter.params.ParameterizedTestParameterResolver@2b974137
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:211)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:144)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:96)

The only solution to this that I can think of would be to have our own equivalent to `@MethodSource` (and, I suppose the other annotations like `@CsvSource`)

**Comment by tombentley** [comment]
My  interpretation of those docs is that the `ArgumentsAggregator` is a contract which allows to map the values provided by an arguments source to some other set of arguments. The provision of the values to the aggregator is still determined by the `@MethodSource` or other source, so the incompatibilty would still exist.

I'll try to find time to confirm this though.

**Comment by k-wall** [comment]
For problem 2, I find that `EnumSource`/`MethodSource` function fine on the condition that they are providing for the first argument:

works:

<img width="2532" alt="Screenshot 2023-03-21 at 18 42 06" src="https://user-images.githubusercontent.com/18440250/226710790-847ddd7b-c4f6-46ec-aa16-808b5f090f00.png">

fails (arg list order change only):

<img width="2532" alt="Screenshot 2023-03-21 at 18 47 33" src="https://user-images.githubusercontent.com/18440250/226711029-6e98444e-4ef6-40f5-b664-8d53588acd32.png">
