### ISSUE TITLE
ParameterExtensionTest is flaky / race condition

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious-junit5-extension#7]
Reported by @SamBarker. Example failure:

```
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka4886149283650868601/broker-0 with metadata.version 3.3-IV0.
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka7298719589906457285/broker-0 with metadata.version 3.3-IV0.
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka7298719589906457285/broker-1 with metadata.version 3.3-IV0.

org.opentest4j.AssertionFailedError: 
Expected :2
Actual   :1
<Click to see difference>


	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at io.kroxylicious.testing.kafka.junit5ext.ParameterExtensionTest.twoDefinedClusterParameterAndAdmin(ParameterExtensionTest.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:30)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

All the failures I've seen related to asserting cluster2 has multiple nodes. Smells like a race condition.

**Comment by tombentley** [comment]
@SamBarker I'm guessing that this could be due to `io.kroxylicious.testing.kafka.invm.InVMKafkaCluster#start` returning before all the brokers have started up sufficiently to be included in the `Metadata` response returned to the `Admin` client. If that's right you should find that io.kroxylicious.testing.kafka.common.KafkaClusterTest#kafkaTwoNodeClusterKraftMode also fails for you. That test currently doesn't current perform the broker number assertion due to the `assumeTrue` failing, so you'd need to comment that out to test it.

**Comment by SamBarker** [comment]
Thanks for the pointers on where to check and confirm, I was guessing at something along those lines.

I guess we need to add [awaitility](http://www.awaitility.org/) or something similar to make sure the clusters are actually ready before injecting them.

I'm happy to add that.

**Comment by tombentley** [comment]
I don't think we need to add a dependency just for a check,sleep loop with a timeout, do we?

**Comment by SamBarker** [comment]
We already have `duct-tape` which offers something close enough.

When testing #9 I get failures such as:

```shell
2022-12-05 12:14:22 WARN  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:160 - Generated config {node.id=0, offsets.topic.num.partitions=1, offsets.topic.replication.factor=1, listener.security.protocol.map=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT, listeners=CONTROLLER://0.0.0.0:52900,EXTERNAL://0.0.0.0:52898,INTERNAL://0.0.0.0:52899, group.initial.rebalance.delay.ms=0, inter.broker.listener.name=INTERNAL, log.dir=/var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka10478054198693657850/broker-0, controller.quorum.voters=0@//localhost:52900, controller.listener.names=CONTROLLER, process.roles=broker,controller, broker.id=0, advertised.listeners=EXTERNAL://localhost:52898,INTERNAL://localhost:52899, early.start.listeners=EXTERNAL,INTERNAL}
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka10478054198693657850/broker-0 with metadata.version 3.3-IV0.
2022-12-05 12:14:23 INFO  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:184 - described cluster: Q2vTkTAQRaaEClVQ3N_DYg and found 1 nodes
2022-12-05 12:14:23 WARN  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:160 - Generated config {node.id=0, offsets.topic.num.partitions=1, offsets.topic.replication.factor=1, listener.security.protocol.map=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT, listeners=CONTROLLER://0.0.0.0:52910,EXTERNAL://0.0.0.0:52906,INTERNAL://0.0.0.0:52908, group.initial.rebalance.delay.ms=0, inter.broker.listener.name=INTERNAL, log.dir=/var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka4823877298554716604/broker-0, controller.quorum.voters=0@//localhost:52910, controller.listener.names=CONTROLLER, process.roles=broker,controller, broker.id=0, advertised.listeners=EXTERNAL://localhost:52906,INTERNAL://localhost:52908, early.start.listeners=EXTERNAL,INTERNAL}
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka4823877298554716604/broker-0 with metadata.version 3.3-IV0.
2022-12-05 12:14:23 WARN  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:160 - Generated config {node.id=1, offsets.topic.num.partitions=1, offsets.topic.replication.factor=1, listener.security.protocol.map=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT, listeners=EXTERNAL://0.0.0.0:52907,INTERNAL://0.0.0.0:52909, group.initial.rebalance.delay.ms=0, inter.broker.listener.name=INTERNAL, log.dir=/var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka4823877298554716604/broker-1, controller.quorum.voters=0@//localhost:52910, controller.listener.names=CONTROLLER, process.roles=broker, broker.id=1, advertised.listeners=EXTERNAL://localhost:52907,INTERNAL://localhost:52909, early.start.listeners=EXTERNAL,INTERNAL}
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka4823877298554716604/broker-1 with metadata.version 3.3-IV0.
2022-12-05 12:14:23 INFO  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:184 - described cluster: sdqh9dQqTGaWm3kOS9GBjg and found 2 nodes

org.opentest4j.AssertionFailedError: 
Expected :2
Actual   :1
<Click to see difference>


	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at io.kroxylicious.testing.kafka.junit5ext.ParameterExtensionTest.twoAnonClusterParameter(ParameterExtensionTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
```

So I think there is something else at play than not waiting for the brokers to be ready.

**Comment by SamBarker** [comment]
Tweaking the logging/assertions a bit implies inconsistent results from describe cluster calls.

```
2022-12-05 13:45:30 WARN  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:145 - Generated config {node.id=0, offsets.topic.num.partitions=1, offsets.topic.replication.factor=1, listener.security.protocol.map=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT, listeners=CONTROLLER://0.0.0.0:57085,EXTERNAL://0.0.0.0:57083,INTERNAL://0.0.0.0:57084, group.initial.rebalance.delay.ms=0, inter.broker.listener.name=INTERNAL, log.dir=/var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka9338812778142749345/broker-0, controller.quorum.voters=0@//localhost:57085, controller.listener.names=CONTROLLER, process.roles=broker,controller, broker.id=0, advertised.listeners=EXTERNAL://localhost:57083,INTERNAL://localhost:57084, early.start.listeners=EXTERNAL,INTERNAL}
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka9338812778142749345/broker-0 with metadata.version 3.3-IV0.
2022-12-05 13:45:30 INFO  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:167 - described cluster: mcSsinoRQEy9tRirUnTKMQ and found 1 nodes in: [localhost:57083 (id: 0 rack: null)]
2022-12-05 13:45:30 WARN  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:145 - Generated config {node.id=0, offsets.topic.num.partitions=1, offsets.topic.replication.factor=1, listener.security.protocol.map=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT, listeners=CONTROLLER://0.0.0.0:57102,EXTERNAL://0.0.0.0:57098,INTERNAL://0.0.0.0:57100, group.initial.rebalance.delay.ms=0, inter.broker.listener.name=INTERNAL, log.dir=/var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka9131807523041917714/broker-0, controller.quorum.voters=0@//localhost:57102, controller.listener.names=CONTROLLER, process.roles=broker,controller, broker.id=0, advertised.listeners=EXTERNAL://localhost:57098,INTERNAL://localhost:57100, early.start.listeners=EXTERNAL,INTERNAL}
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka9131807523041917714/broker-0 with metadata.version 3.3-IV0.
2022-12-05 13:45:30 WARN  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:145 - Generated config {node.id=1, offsets.topic.num.partitions=1, offsets.topic.replication.factor=1, listener.security.protocol.map=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT, listeners=EXTERNAL://0.0.0.0:57099,INTERNAL://0.0.0.0:57101, group.initial.rebalance.delay.ms=0, inter.broker.listener.name=INTERNAL, log.dir=/var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka9131807523041917714/broker-1, controller.quorum.voters=0@//localhost:57102, controller.listener.names=CONTROLLER, process.roles=broker, broker.id=1, advertised.listeners=EXTERNAL://localhost:57099,INTERNAL://localhost:57101, early.start.listeners=EXTERNAL,INTERNAL}
Formatting /var/folders/1g/2nsqtt916vg8f5bftn1tp0580000gn/T/kafka9131807523041917714/broker-1 with metadata.version 3.3-IV0.
2022-12-05 13:45:30 INFO  io.kroxylicious.testing.kafka.invm.InVMKafkaCluster:167 - described cluster: 32xnI2vhR3y9KtmgZc4b0A and found 2 nodes in: [localhost:57098 (id: 0 rack: null), localhost:57099 (id: 1 rack: null)]

java.lang.AssertionError: 
Expected size: 2 but was: 1 in:
[localhost:57098 (id: 0 rack: null)]
```

**Comment by SamBarker** [comment]
Talking this over with @showuon we are suspicious that my fix is not enough due to eventual consistency artefacts as the cluster metadata is replicated. Our thinking was during the investigation we could observe the `describeCluster` call which found two nodes was answered by `node 0` but the failing request was answered by `node 1`. 

> Because brokers are registering to controllers -> controller write "broker x registered in the cluster" metadata log into metadata topic -> and then, brokers can pull from the metadata topic to get the broker x registered info -> broker update metadata cache

We haven't come up with any sensible fixes for this issue. Obviously we can add a wait until to the flaky test but that somewhat defeats the purpose of the extension by not delivering a fully functional cluster. 

The other option we discussed was to change the admin client usage in [`InVMCluster.start`](https://github.com/kroxylicious/kroxylicious-junit5-extension/pull/9/files#diff-adb515c888110e435a080b0768331310cd72266d34c7d1d5653d5e017db67576R164) to bootstrap directly to each broker and poll each broker until each one had returned the requisite number of nodes.

**Comment by tombentley** [comment]
Thanks for the investigation! I wonder whether this is something that should be part of the `KafkaCluster` contract or not. Given the eventual consistency behaviour is intrinsic to how Kafka/KRaft works then trying to provide a better guarantee in `KafkaCluster` would mean people were testing their code with a guarantee that a real Kafka cluster doesn't actually provide. So we'd be creating the possibility of false positives. Perhaps it's a better compromise to offer a helper function that people can call in their tests if they really need to block for consistent metadata responses. That would be something they'd be opting into explicitly, rather than doing it for them implicitly. It also means that by default we wouldn't be delaying entry to the `@Test` method on a check that might not be necessary. 

We'd also document on `KafkaCluster` and the `README` that this behaviour was possible. Wdyt @SamBarker @showuon?

**Comment by showuon** [comment]
> I suspect your suggestion of a helper/utility method to do the polling for users to allow them to assert their pre-conditions is a good compromise.

+1
